version: "2.15"
services:
  react-ui:
    build:
      context: ./front
    environment:
      - VITE_SERVER_URL=''
      - VITE_SERVER_REFRESH_TOKEN=''
    ports:
      - "3000:3000"
    container_name: auth-ui
    stdin_open: true
  api:
    build:
      context: ./back
    environment:
      - AUTHSYS_DATABASE_URL=
      - AUTHSYS_TOKEN_SECRET=
      - AUTHSYS_COOKIE_NAME=
    ports:
      - "8080:8080"
    container_name: auth-api
    stdin_open: true
