version: "2.15"
services:
  react-ui:
    build:
      context: ./front
    ports:
      - "80:3000"
    container_name: auth-ui
    stdin_open: true
  #api:
  # build:
  #  context: ./back
  #ports:
  # - "8080:8080"
  #container_name: auth-api
  #stdin_open: true
