services:
  api:
    build:
      context: ./back
    ports:
      - "8080:8080"
    container_name: auth-api
    links:
      - db
    stdin_open: true
    depends_on:
      - db

  react-ui:
    build:
      context: ./front
    ports:
      - "3000:80"
    container_name: auth-ui
    stdin_open: true

volumes:
  db:
    driver: local
